name: Weekly Sync with Upstream

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Sync type'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - main-only
          - feature-only
      create_release:
        description: 'Create GitHub release'
        required: false
        default: false
        type: boolean
      create_pr:
        description: 'Create PR if feature updates available'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run sync script
        env:
          SYNC_TYPE: ${{ github.event.inputs.sync_type || 'full' }}
          CREATE_RELEASE: ${{ github.event.inputs.create_release || 'false' }}
          CREATE_PR: ${{ github.event.inputs.create_pr || 'false' }}
        run: |
          CMD="./scripts/manual-sync.sh -t $SYNC_TYPE"
          if [[ "$CREATE_RELEASE" == "true" ]]; then
            CMD="$CMD -r"
          fi
          if [[ "$CREATE_PR" == "true" ]]; then
            CMD="$CMD -p"
          fi
          eval "$CMD"

      - name: Build and test
        run: |
          npm run build
          npm test -- --testPathPattern="openRouter" || echo "OpenRouter tests not found or failed"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Sync failed. Check the logs above for details."
          echo "You may need to resolve conflicts manually."
